apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer-try-to-see-me
spec:
  acme:
    email: a.abdulsatarov.b@gmail.com
    privateKeySecretRef:
      name: my-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx