apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: bitnami/rabbitmq:3.11.18
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
