apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingressClassName: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: 178.128.143.70
      http:
        paths:
          - path: /api/?(.*)
            pathType: Prefix
            backend:

              service:
                name: api-gateway-service
                port:
                  number: 8080
